
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: htri7_development

test:
  <<: *default
  database: htri7_test

production:
  <<: *default
  database: htri7_production
